site_name: Allegro REST API Design Guidelines
theme: material
docs_dir: ./docs

nav:
- Introduction: 'Allegro REST API Design Guidelines.md'
- Contents: 'Contents.md'
- Resource: 'Resource.md'
- Representation: 'Representation.md'
- Error: 'Error.md'