site_name: Allegro REST API Design Guidelines
theme: material
docs_dir: ./docs

nav:
- Allegro REST API Design Guidelines: 'Allegro REST API Design Guidelines.md'
- Contents: 'Contents.md'
- Resource: 'Resource.md'