site_name: Allegro REST API Design Guidelines
theme: material
docs_dir: ./docs

nav:
- Introduction: 'index.md'
- Resource: 'Resource.md'
- Representation: 'Representation.md'
- Error: 'Error.md'
- Command pattern: 'Command pattern.md'
- Documentation: 'Documentation.md'
- Glossary: 'Glossary.md'
- HATEOAS: 'HATEOAS.md'