name: Deploy edge-docs to Github Pages

on:
  push:
    branches: [ master ]
    paths: ['docs/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, linux, 8gb]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: mkdocs gh-deploy --force